export const auditorsRemarksStandalone = {
  years: [2024, 2020, 2025, 2021, 2016, 2022, 2017, 2018, 2023, 2019],
  rows: [
    {
      label: "Whether Auditors Report has been Qualified ?",
      values: ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
    },
  ],
};

export const complianceKpis = [
  {
    label: "Total GSTIN",
    value: 48,
    variant: "blue",
  },
  {
    label: "Active GSTIN",
    value: 31,
    variant: "red",
  },
  {
    label: "Inactive GSTIN",
    value: 17,
    variant: "purple",
  },
];

export const pendingCasesTable = [
  {
    caseNumber: "202900000462025",
    petitioner: "M P Consumer Products Through Proprietor...",
    respondent: "Dabur India Ltd Through Shri Mohit Barma",
    year: 2025,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200200031232024",
    petitioner: "Om Jhawar",
    respondent: "Dabur India Limited and 1 more",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200101065112024",
    petitioner: "Lkp Securities Limited, Throughdinesh Wa...",
    respondent: "Dabur India Ltd and 2 more",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200415000552024",
    petitioner: "Union Of India At The Instance Of Sh Swa...",
    respondent: "Dabur India Limited and 14 more",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "204600000592024",
    petitioner: "Commissioner Of Central Excise, Kolkata ...",
    respondent: "M/S Dabur India Limited",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "204600000582024",
    petitioner: "Commissioner Of Central Excise Kolkata V...",
    respondent: "M/S Dabur India Limited",
    year: 2024,
    court: "DistrictCourt",
  },

  {
    caseNumber: "200101012232024",
    petitioner: "Dr. Eddie Pheroze Bharucha (Deleted)",
    respondent: "Gateway Travels And Tours Pvt. Ltd.",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200101012232024",
    petitioner: "Vishal Chaudhary",
    respondent: "Dabur India Limited",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "207800001052024",
    petitioner: "A.K.Sharma",
    respondent: "M/S Dabur India Ltd.",
    year: 2024,
    court: "DistrictCourt",
  },
];

export const activeGstTable = [
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Active",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Active",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
];

export const inactiveGstTable = [
  {
    gstin: "18AAACD0474C1Z4",
    state: "-",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Cancelled on application of Taxpayer",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Cancelled",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Jammu and Kashmir",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Not Migrated",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "-",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Cancelled on application of Taxpayer",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Cancelled",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Jammu and Kashmir",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Not Migrated",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "-",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Cancelled on application of Taxpayer",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Cancelled",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Jammu and Kashmir",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Not Migrated",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Jammu and Kashmir",
    lastFiling: "-",
    dueDate: "-",
    delay: "-",
    status: "Not Migrated",
  },
];

export const activeEstablishmentTable = [
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Active",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Active",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Active",
  },
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Active",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Active",
  },
];

export const inactiveEstablishmentTable = [
  {
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Inactive",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Inactive",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Inactive",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Inactive",
  },{
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Inactive",
  },
  {
    gstin: "29BBDDC158D2A5",
    state: "Mizoram",
    lastFiling: "15 Dec 2025",
    dueDate: "15 Dec 2025",
    delay: "Delay in Filing",
    status: "Inactive",
  },
  {
    gstin: "47CCEDD269E3B6",
    state: "Nagaland",
    lastFiling: "20 Jan 2026",
    dueDate: "20 Jan 2026",
    delay: "Delay in Filing",
    status: "Inactive",
  },
  {
    gstin: "56DDFEE3707F4C7",
    state: "Uttar Pradesh",
    lastFiling: "25 Feb 2026",
    dueDate: "25 Feb 2026",
    delay: "Delay in Filing",
    status: "Inactive",
  },{
    gstin: "18AAACD0474C1Z4",
    state: "Assam",
    lastFiling: "11 Nov 2025",
    dueDate: "11 Nov 2025",
    delay: "No delay",
    status: "Inactive",
  },
 
];
