export const auditorsRemarksStandalone = {
  years: [2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016],
  rows: [
    {
      label: "Whether Auditors Report has been Qualified ?",
      values: [
        "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"
      ],
    },
  ],
};

export const complianceKpis = [
  {
    label: "Total GSTIN",
    value: "-",
    variant: "blue",
  },
  {
    label: "Active GSTIN",
    value: "-",
    variant: "red",
  },
  {
    label: "Inactive GSTIN",
    value: "-",
    variant: "purple",
  },
];

export const pendingCasesTable = [
  {
    caseNumber: "202900000462025",
    petitioner: "M P Consumer Products Through Proprietor...",
    respondent: "Dabur India Ltd Through Shri Mohit Barma",
    year: 2025,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200200031232024",
    petitioner: "Om Jhawar",
    respondent: "Dabur India Limited and 1 more",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200101065112024",
    petitioner: "Lkp Securities Limited, Throughdinesh Wa...",
    respondent: "Dabur India Ltd and 2 more",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200415000552024",
    petitioner: "Union Of India At The Instance Of Sh Swa...",
    respondent: "Dabur India Limited and 14 more",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "204600000592024",
    petitioner: "Commissioner Of Central Excise, Kolkata ...",
    respondent: "M/S Dabur India Limited",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "204600000582024",
    petitioner: "Commissioner Of Central Excise Kolkata V...",
    respondent: "M/S Dabur India Limited",
    year: 2024,
    court: "DistrictCourt",
  },

  {
    caseNumber: "200101012232024",
    petitioner: "Dr. Eddie Pheroze Bharucha (Deleted)",
    respondent: "Gateway Travels And Tours Pvt. Ltd.",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "200101012232024",
    petitioner: "Vishal Chaudhary",
    respondent: "Dabur India Limited",
    year: 2024,
    court: "DistrictCourt",
  },
  {
    caseNumber: "207800001052024",
    petitioner: "A.K.Sharma",
    respondent: "M/S Dabur India Ltd.",
    year: 2024,
    court: "DistrictCourt",
  },
];

export const activeGstTable = [
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Active",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Active",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
];

export const inactiveGstTable = [
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "-",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Cancelled on application of Taxpayer",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Cancelled",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Jammu and Kashmir",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Not Migrated",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "-",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Cancelled on application of Taxpayer",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Cancelled",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Jammu and Kashmir",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Not Migrated",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "-",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Cancelled on application of Taxpayer",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Cancelled",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Jammu and Kashmir",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Not Migrated",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Jammu and Kashmir",
  //   lastFiling: "-",
  //   dueDate: "-",
  //   delay: "-",
  //   status: "Not Migrated",
  // },
];

export const activeEstablishmentTable = [
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Active",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Active",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Active",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Active",
  // },
];

export const inactiveEstablishmentTable = [
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "29BBDDC158D2A5",
  //   state: "Mizoram",
  //   lastFiling: "15 Dec 2025",
  //   dueDate: "15 Dec 2025",
  //   delay: "Delay in Filing",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "47CCEDD269E3B6",
  //   state: "Nagaland",
  //   lastFiling: "20 Jan 2026",
  //   dueDate: "20 Jan 2026",
  //   delay: "Delay in Filing",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "56DDFEE3707F4C7",
  //   state: "Uttar Pradesh",
  //   lastFiling: "25 Feb 2026",
  //   dueDate: "25 Feb 2026",
  //   delay: "Delay in Filing",
  //   status: "Inactive",
  // },
  // {
  //   gstin: "18AAACD0474C1Z4",
  //   state: "Assam",
  //   lastFiling: "11 Nov 2025",
  //   dueDate: "11 Nov 2025",
  //   delay: "No delay",
  //   status: "Inactive",
  // },
];

export const csrDetails2021_22 = [
  // {
  //   state: "Assam",
  //   sector: "Art And Culture",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Assam",
  //   sector: "Health Care",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Assam",
  //   sector: "Livelihood Enhancement Projects",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Assam",
  //   sector: "Poverty, Eradicating Hunger, Malnutrition",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Assam",
  //   sector: "Training To Promote Sports",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Bihar",
  //   sector: "Health Care",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Delhi",
  //   sector: "Health Care",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
  // {
  //   state: "Himachal Pradesh",
  //   sector: "Environmental Sustainability",
  //   project: "Traditional Folk Dance Workshop - Assam",
  //   amountSpent: "100000.00",
  //   outlay: "-",
  // },
];

export const creditRatingDates = [
  "2023-11-24",
  "2023-04-04",
  "2022-04-29",
  "2021-05-27",
  "2020-05-19",
  "2019-05-30",
  "2018-06-22",
  "2017-06-23",
  "2016-06-08",
];

export const creditRatings = {
  CRISIL: {
    "2023-11-24": [
      // {
      //   category: "DI - COMMERCIAL PAPER / ST",
      //   amount: "200.0",
      //   rating: "A1+",
      //   action: "REAFFIRMED",
      // },
      // {
      //   category: "DI - BONDS/NCD / LT",
      //   amount: "20.0",
      //   rating: "AAA (Stable)",
      //   action: "REAFFIRMED",
      // },
      // {
      //   category: "BLR - BANK GUARANTEE / ST",
      //   amount: "32.5",
      //   rating: "A1+",
      //   action: "REAFFIRMED",
      // },
      // {
      //   category: "BLR - BANK FACILITY / LT",
      //   amount: "125.0",
      //   rating: "AAA (Stable)",
      //   action: "REAFFIRMED",
      // },
    ],
  },

  ICRA: {
    "2023-11-24": [
      // {
      //   category: "DI - COMMERCIAL PAPER / ST",
      //   amount: "150.0",
      //   rating: "A1+",
      //   action: "REAFFIRMED",
      // },
    ],
  },
};


export const epfoYearlyTableData = [
  // {
  //   year: "2025-2026",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 1,
  // },
  // {
  //   year: "2024-2025",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 2,
  // },
  // {
  //   year: "2023-2024",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 2,
  // },
  // {
  //   year: "2022-2023",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 9,
  // },
  // {
  //   year: "2021-2022",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 8,
  // },
  // {
  //   year: "2020-2021",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 5,
  // },
  // {
  //   year: "2019-2020",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 7,
  // },
  // {
  //   year: "2018-2019",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 7,
  // },
  // {
  //   year: "2017-2018",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 7,
  // },
  // {
  //   year: "2016-2017",
  //   employees: 5738,
  //   contribution: "33,146,773",
  //   delay: 7,
  // },
];
